import type { RelationshipType } from "./document";

/** Couple / partnership bars (not parent, not pure emotional). */
export const COUPLE_TYPES: ReadonlySet<RelationshipType> = new Set([
  "marriage",
  "engagement",
  "separation",
  "separationInFact",
  "divorce",
  "widowed",
  "cohabitation",
  "legalCohabitation",
  "engagementCohabitation",
  "engagementSeparation",
  "loveAffair",
]);

export const RELATIONSHIP_LABELS: Record<RelationshipType, string> = {
  marriage: "婚姻",
  engagement: "訂婚",
  separation: "法律分居",
  separationInFact: "事實分居",
  divorce: "離婚",
  widowed: "喪偶",
  cohabitation: "同居",
  legalCohabitation: "法律同居",
  engagementCohabitation: "訂婚同居",
  engagementSeparation: "訂婚分居",
  loveAffair: "婚外情",
  parent: "親子",
  adoptiveParent: "收養親子",
  twin: "雙胞胎",
  harmony: "和諧",
  indifferent: "冷漠",
  love: "愛",
  inLove: "戀愛中",
  close: "親密/友誼",
  veryClose: "非常親密",
  conflict: "衝突",
  hate: "憎恨",
  cutoff: "斷絕/疏遠",
  hostile: "敵對",
  distantHostile: "遠距敵對",
  closeHostile: "近距敵對",
  fusedHostile: "融合敵對",
  violence: "暴力",
  abuse: "虐待",
  physicalAbuse: "肢體虐待",
  emotionalAbuse: "情感虐待",
  sexualAbuse: "性虐待",
  neglect: "忽視",
  manipulative: "操控",
  controlling: "控制",
  focusedOn: "關注",
  fanAdmire: "仰慕",
};

export const FAMILY_REL_OPTIONS: { value: RelationshipType; label: string }[] = [
  { value: "marriage", label: "婚姻" },
  { value: "engagement", label: "訂婚" },
  { value: "separationInFact", label: "事實分居" },
  { value: "separation", label: "法律分居" },
  { value: "divorce", label: "離婚" },
  { value: "engagementSeparation", label: "訂婚分居" },
  { value: "widowed", label: "喪偶" },
  { value: "engagementCohabitation", label: "訂婚同居" },
  { value: "cohabitation", label: "同居" },
  { value: "legalCohabitation", label: "法律同居" },
  { value: "loveAffair", label: "婚外情" },
  { value: "parent", label: "親子" },
  { value: "adoptiveParent", label: "收養親子" },
  { value: "twin", label: "雙胞胎" },
];

export const EMOTION_REL_OPTIONS: { value: RelationshipType; label: string }[] =
  [
    { value: "harmony", label: "和諧" },
    { value: "indifferent", label: "冷漠" },
    { value: "love", label: "愛" },
    { value: "inLove", label: "戀愛中" },
    { value: "close", label: "親密/友誼" },
    { value: "veryClose", label: "非常親密" },
    { value: "conflict", label: "衝突" },
    { value: "hate", label: "憎恨" },
    { value: "cutoff", label: "斷絕/疏遠" },
    { value: "hostile", label: "敵對" },
    { value: "distantHostile", label: "遠距敵對" },
    { value: "closeHostile", label: "近距敵對" },
    { value: "fusedHostile", label: "融合敵對" },
    { value: "violence", label: "暴力" },
    { value: "abuse", label: "虐待" },
    { value: "physicalAbuse", label: "肢體虐待" },
    { value: "emotionalAbuse", label: "情感虐待" },
    { value: "sexualAbuse", label: "性虐待" },
    { value: "neglect", label: "忽視" },
    { value: "manipulative", label: "操控" },
    { value: "controlling", label: "控制" },
    { value: "focusedOn", label: "關注" },
    { value: "fanAdmire", label: "仰慕" },
  ];

export const ALL_REL_OPTIONS: { value: RelationshipType; label: string }[] = [
  ...FAMILY_REL_OPTIONS,
  ...EMOTION_REL_OPTIONS,
];

export const FAMILY_REL_LEGEND = [
  { key: "biological", label: "親生", detail: "單實線" },
  { key: "adoptive", label: "收養", detail: "實線＋平行虛線" },
  { key: "twin", label: "雙胞胎", detail: "共用分岔" },
] as const;
